version: '3.8'

services:
  supersell_database:
    image: postgres
    container_name: supersell_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=supersell_admin
      - POSTGRES_PASSWORD=2448priviet
      - POSTGRES_DB=supersell
    volumes:
      - pgdata:/data/postgres

  # supersell_server:
  #   build: .
  #   container_name: supersell_server
  #   ports:
  #     - 3333:3000
  #   volumes:
  #     - .:/usr/app

# networks:
#   mynetwork:
#     driver: bridge

volumes:
  pgdata:
    driver: local
